version: "3"
services:
  nestjs:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always
  grafana:
    image: grafana/grafana:8.1.3
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always
    env_file: 
      .env
